import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';

import { StatePanel } from '../components/common/StatePanel';
import { StatusBadge } from '../components/common/StatusBadge';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import type { Alert, EventRecord, InvestigationNote } from '../types/api';

export function AlertDetailPage() {
  const { alertId = '' } = useParams();
  const { token, user } = useAuth();
  const [alert, setAlert] = useState<Alert | null>(null);
  const [events, setEvents] = useState<EventRecord[]>([]);
  const [notes, setNotes] = useState<InvestigationNote[]>([]);
  const [noteDraft, setNoteDraft] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      if (!token || !alertId) return;
      setLoading(true);
      setError(null);
      try {
        const [alertData, eventData, noteData] = await Promise.all([
          api.getAlert(token, alertId),
          api.getEvents(token),
          api.getNotes(token, alertId),
        ]);
        setAlert(alertData);
        setEvents(eventData);
        setNotes(noteData);
      } catch {
        setError('Unable to load alert investigation context.');
      } finally {
        setLoading(false);
      }
    }
    void load();
  }, [alertId, token]);

  const linkedEvent = useMemo(
    () => events.find((event) => event.id === alert?.event_id),
    [alert?.event_id, events],
  );

  async function handleAddNote(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!token || !alertId || !noteDraft.trim()) return;

    const created = await api.createNote(token, alertId, noteDraft.trim());
    setNotes((prev) => [created, ...prev]);
    setNoteDraft('');
  }

  if (loading) return <StatePanel title="Loading investigation" description="Collecting alert evidence..." />;
  if (error || !alert) {
    return <StatePanel title="Investigation unavailable" description={error ?? 'Alert not found.'} tone="error" />;
  }

  return (
    <section>
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-semibold">{alert.title}</h2>
          <p className="mt-1 text-sm text-slate-400">Alert #{alert.id} investigation workspace</p>
        </div>
        <Link to="/alerts" className="text-sm text-cyan-300 hover:underline">
          Back to alerts
        </Link>
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <div className="rounded-lg border border-slate-800 bg-slate-900 p-4 xl:col-span-2">
          <h3 className="text-sm font-semibold text-slate-300">Alert Metadata</h3>
          <div className="mt-3 grid gap-3 text-sm md:grid-cols-2">
            <p>
              <span className="text-slate-400">Status:</span> <StatusBadge value={alert.status} variant="status" />
            </p>
            <p>
              <span className="text-slate-400">Severity:</span>{' '}
              <StatusBadge value={alert.severity} variant="severity" />
            </p>
            <p className="text-slate-300">
              <span className="text-slate-400">Created:</span> {new Date(alert.created_at).toLocaleString()}
            </p>
            <p className="text-slate-300">
              <span className="text-slate-400">Linked Event ID:</span> {alert.event_id}
            </p>
          </div>
          <p className="mt-4 text-sm text-slate-300">{alert.description}</p>
        </div>

        <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
          <h3 className="text-sm font-semibold text-slate-300">Detection Explanation</h3>
          <p className="mt-2 text-sm text-slate-400">
            This alert was generated by the backend detection pipeline and should be validated against source
            telemetry, actor context, and host behavior before escalation.
          </p>
        </div>
      </div>

      <div className="mt-4 rounded-lg border border-slate-800 bg-slate-900 p-4">
        <h3 className="text-sm font-semibold text-slate-300">Linked Event</h3>
        {linkedEvent ? (
          <div className="mt-3 grid gap-2 text-sm text-slate-300 md:grid-cols-2">
            <p>
              <span className="text-slate-400">Type:</span> {linkedEvent.event_type}
            </p>
            <p>
              <span className="text-slate-400">Actor:</span> {linkedEvent.actor}
            </p>
            <p>
              <span className="text-slate-400">Source IP:</span> {linkedEvent.source_ip}
            </p>
            <p>
              <span className="text-slate-400">Occurred:</span> {new Date(linkedEvent.occurred_at).toLocaleString()}
            </p>
          </div>
        ) : (
          <StatePanel title="No linked event" description="Event context is unavailable for this alert." />
        )}
      </div>

      <div className="mt-4 rounded-lg border border-slate-800 bg-slate-900 p-4">
        <h3 className="text-sm font-semibold text-slate-300">Investigation Notes</h3>

        {user?.role !== 'viewer' ? (
          <form onSubmit={handleAddNote} className="mt-3 flex flex-col gap-2">
            <textarea
              value={noteDraft}
              onChange={(event) => setNoteDraft(event.target.value)}
              placeholder="Add analyst note, rationale, and next action."
              className="min-h-24 rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm"
            />
            <button className="self-start rounded bg-cyan-500 px-3 py-2 text-sm font-medium text-slate-950 hover:bg-cyan-400">
              Add Note
            </button>
          </form>
        ) : null}

        {notes.length === 0 ? (
          <div className="mt-3">
            <StatePanel title="No notes yet" description="Capture investigation findings and remediation steps." />
          </div>
        ) : (
          <ul className="mt-4 space-y-3">
            {notes.map((note) => (
              <li key={note.id} className="rounded border border-slate-800 bg-slate-950 p-3 text-sm">
                <p className="text-slate-200">{note.note}</p>
                <p className="mt-1 text-xs text-slate-500">{new Date(note.created_at).toLocaleString()}</p>
              </li>
            ))}
          </ul>
        )}
      </div>
    </section>
  );
}
